# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/gorilla/mux";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/mux";
      rev = "75dcda0896e109a2a22c9315bca3bb21b87b2ba5";
      sha256 = "1d0sy1paa055ic84sp3766s9pa24q008hf77dc842vrgvn8p3wmh";
    };
  }
  {
    goPackagePath = "github.com/gorilla/websocket";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/websocket";
      rev = "b65e62901fc1c0d968042419e74789f6af455eb9";
      sha256 = "0mkm9w6kjkrlzab5wh8p4qxkc0icqawjbvr01d2nk6ykylrln40s";
    };
  }
  {
    goPackagePath = "github.com/hpcloud/tail";
    fetch = {
      type = "git";
      url = "https://github.com/hpcloud/tail";
      rev = "a1dbeea552b7c8df4b542c66073e393de198a800";
      sha256 = "0nssmn8j0yavs8099gwb69qpd1k9yd2z28bii6i4y61v0grb6bc2";
    };
  }
  {
    goPackagePath = "github.com/jinzhu/gorm";
    fetch = {
      type = "git";
      url = "https://github.com/jinzhu/gorm";
      rev = "7ea143b5484fe28148d5c73cfd43b26e8a89c94e";
      sha256 = "1bvi9x0cayw8pj6ls4wn2rmpnwwhxqxwg0493qv6yy0c07l5kiqb";
    };
  }
  {
    goPackagePath = "github.com/jinzhu/inflection";
    fetch = {
      type = "git";
      url = "https://github.com/jinzhu/inflection";
      rev = "196e6ce06ca4513fbcfcbc35dc15f66074df47c9";
      sha256 = "0schhmz8wm2iz3pxrgx9ngrlp42n5myvvsr7a6jwp61y3fr4lls5";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-sqlite3";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-sqlite3";
      rev = "98a44bcf5949f178c8116fa30e62c9ac2ef65927";
      sha256 = "108rk74ringkkyx05zlq5khh32fsfi0przyzrpsr1r5j57xrhxj0";
    };
  }
]
